language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
  - secure: cWNW9J6N0HGem2C+/x6M4zKKCcfqISyz5kEa0wWnjkOPQROSoEtBvPc8sJxoBmwINBXT4GhgY3A/z1brTlGq1Iwua9QOJtPSuExIul8rBcnywWqWa/HxRRHQcE6juel+v6u6+jms7vB7/nJqsXJ+LMemIr9Y48NlVXglas+hdRQE8LEqP/ilroek9vqwfU+xkNfW9/oFCtKgpUaEINOVCCs+wiHAqse9rrlSg2E5D1IfMkwSuOb5A4BmEHWH8aGcT8RO59rn6rQhsscoi7K0ysS6+mQgcTFcU3Mqh8EgDanoyKkBjjm+Ht2J8ResNKookYQDjoB6SCC9mfeGxtZoezgBQVIpFHKvEtf0ZjTUdJY2kSppp4YZdE9HRPUfi+NGNPE9jODZG558fYMmkMGQiPVqUVeOQZlXgbGiPRfX21BNjyO9qzEGJaBGYJ0gX4U2g9Njzyb52nY022OvdJafBvCsGizU9Z2LBR9utM2qP5x68HgGdQHboybx/OfMS8DsB38PPsTIQ+NsO4V/kdaMgZMqx8PoZyHcvicDJ4D3ua9U6lzflgotQTdsM0x2C6Tbk16YkU8fvMYJRyWBDwPib9F3PIe8A+/coZ8DFtQwMVCg+s411jlWNOt6rh7UmUCRJaR+UDBHwpodjZd35PD1tPXZ/ff7h4vZEghCVZ/OvBw=
  - secure: A2w68kpGFLdykosdhOtu4xO4xAom87b+/watOES5ECykcToBt7U8VHKT3brn4o8bACtbhLfHxtnb2Rq+Fuam/amm8JLSJ0EJJ5wplWq92loXIqi5L9cprEbT7UeGlMcdIKkLNlL+MLFKrk2zSi4UuJ4XPdmE3ZgJMcdhD3a5bI3vCqJ3TCiSOKbCMAvjO+TEnga2b8AZ0sPy2a8tLLxKElCO0eVHC/yQKcXWDBPrLwuAJo+bJwSVZsYSu7k2ED2NupYN4IcIxGymE+motJ3iviJpXad4yijNt2tZbOyeozKwReC6J6CmTnZBv5ePKXfg+FAHTyt2B0Jjo7ArD7zma942NAXuLfXyNzWWVkxa1wQGLaH19V4wIqBiZ74rV/yiwWmNrIrYhWu8LaF1I7sEOss57PzhVT9uIafADfT/KRLvx0rsP0KjT5R2A5kGKdA64QDVqK1zsZ3XtJ99z+V0kMxhXy1A0tx/srFFt4+zrtq1/K0MZhnlbP0EGfODyg+gOGWCpHJmVMac4Zn97umpVfLbilyCu/x39bSmf6MV5nTxgsVr27knLtiCzYRi2yxlBTjhJZSEUWn+b5D3Lxsk4KS0hbHw6PF4rogKO+0UkFZplvyxPtVh2tC8YQm+9ZJdhlJK7A3ZE/KSSWYbveSK4Lc8ApWW1JJ75equ8MAZaYk=
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: i3cz8q4kneNW0OJzU14W3cxPANpMrEy4oPnPv5u8ykDUkbVOLeGv9eD/n9s++H6EJwDrrA13+77MBbRMEvTI1jC/yXUmhxjUPFDE+jNepwQp+Otd2sNMGROOglv610OSGS1geBK+Pdo0QnLMqzop1y0fht8ZuEKoWKvGguFOch34yE0q7rrN2RIW8rZQ2JxU2a7BzG9Yz7VNB0+ArvFKYvBOpslncBXX5xXpO0EXzvRb9s6djo991x6B/f1DiJNO4zFyqPVbsbHUdxd7Oznr5YAezj/cztm9jSFHt7pBCeadDrp5OfBnuUDM/KJwhWXFxO3VVRvRFXRJi5U4EVtPb06iaTpUQJ9KRpxZwwvoV7rmRANxNDJOTKFhwuymkqjHLJSgH5IcJHIRXRLSsYu9SND++3iuOw0z4KbdnCMe1JDNhIqM+0slkjwt44oOsISwfBhk6FeBqZTKZHWzkSv6Rpbs7OTSYvmpk19T3Lodmmb8GU7Z88fqgosXijk6yJS2MVp+mrbPJvipNfwoAEXh+Jzu0xoNyeidsguhVpQGenWrWGT/c9TVPQHQYklxC1IdIQ4d6JRMlmurPjU2PSuX51uJsoRFpsUpn+ItBGhkNj79ZPCODszfs8qcuBckgWgjybzf91rsM0YTNuua6qmFNlwgbOkcL1Foz1La5ZhSOYI=
  on:
    repo: FreeAllMedia/almaden
    branch: master
