language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
    - secure: dRjXIeJQ1Ke4Fc6AHKgMiXtSjbdej7rSfTZwn/AYDMFAWWV2ETTBDLo0rPBpocnbk1XEi+tMjq+gBzyWstJPK+xuwIa2UVKBc5XmXbRbzTn1FaXbZdmPw/a0XTIDOqvQK1mkgP5hfEvicSGt7yyG/DuG+S9R2Q4O+hSq0gWvaGLHS3iScRz2Y2LjGo5H4B4EpnTDlQyBSY01mn4dh1aQn3dMGXmlgwQTByEuFKIDAgHh4LtbaXknm5gtjZY10V4nhLyBNkVrci63Ji7lIvll1Np9puoeEg8EkIkmA5ElnJZ5phNmfFT0UaBiYxVMUdiOK3lmuIeCL1hrYgSMF8avWhWkTefquSDN5jtAYT3yxhnshyBCz54Yllf41IiPjQqVa7TwNY3ZFI0hmyM9+/0VTa5N+Ksg/ispNngRkRbKr9TBuZOmX2fXbOCxtLc461SlHKEp5AnXP8jlu9Slakv93Sid/B8HLuTHxOdBeWOpyJz5mEWCUcGhR4b1ZYJAvCSoxV1lNNR1iEbPjpXhdIVO2Ke4dwQPcDRVN1I16B4bEIbyOPCajmvP659ZLSmL1n95bS7FJts3qzYlEPrLyMT2yh4HVq+SqHUI21yJlXUJA6RBhzS/ZE7u1nGLR4C8Ha0owONpqS9doWnQlkAQA1OU8S4WvLikKTkU1b+KmDZb1eU=
    - secure: t5dBz8kEjET+cEObCndu1vrgGrtJoSSalmNY+bqD+CfGP0np3+3vV8UV6qFGpyx9/MIbgF8klGaFgVllKmF1MmIqyV8HPHJMnj6VYY68LWrU464/iYGhNdvjPodnRwgrpGjoBKklmhwtWRY62McYIiJAkN72lKALrjUAGSjI+jDMaJUBGVD/yarBCcxuF7j2MoTFaYGnO2fmqUhAFtXoJQGtVP/539o77+uQWbCADOgzFIL5k7aY85wcU+agyk7tVe1sUFarjF54djaaejHYQXIyAn5RH4NXhbkT3zxiJEkTSYOOgUwEy6IgZwYJ+zCtB+Dd+2UFnxIKjdDJ5IFJKZCpCxCCyfe15eyx9alWdlO48f/POe3ZjFaar2L3E08cXxoB37Uww/ijw/B2IN8KgA1m/D1k7vnaEz8a7+7XckCMZdAeOh1THFpc0ZOGh2jPBUqUPl7+k/QDBqiVw/dv1L/5OMmto7FM5lxAmZBD6CA/JDUlxs4H1dvz68cFC7gOCM0LFbxOWFfK20mZxv3NgT/HuNw6iMJ33kwlep4nzGQuF/SmsiGMxVYMXndcXBqZ4WBgTH0MmKY5v4qGgZyF7xfNC81Iir2D2esCa33tGz2+78cxFaOwtT/SjpZGGwJpNXXOcFPJaRlpXMGo0uF5GX1eoF2YNDJhuc3KT/ceDSw=
